variables:
  DOCKER_REGISTRY: "privaterepo.example.com"

image: docker

stages:
  - deploy

deploy-master:
  stage: deploy
  only:
    - master
  script:
    - docker login --username=$DOCKER_USER --password=$DOCKER_PASS $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME .
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

deploy-except-master:
  stage: deploy
  except:
    - master
  script:
    - docker login --username=$DOCKER_USER --password=$DOCKER_PASS $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
